--- #YAML:1.0
name: Catalyst-Plugin-DefaultEnd
version: 0.04
author:
  - Marcus Ramberg <marcus@thefeed.no>
abstract: Sensible default end action.
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
