---
name: Catalyst-Plugin-DefaultEnd
version: 0.02
author:
  - Marcus Ramberg <marcus@thefeed.no>
abstract: Sensible default end action.
license: perl
requires:
  Catalyst: 5.2
provides:
  Catalyst::Plugin::DefaultEnd:
    file: lib/Catalyst/Plugin/DefaultEnd.pm
    version: 0.02
generated_by: Module::Build version 0.2607
